@startuml components
skinparam componentStyle rectangle

component [template-service\n:8081] as TS {
  [IngestionTemplateController]
  [IngestionTemplateService]
}

component [ingestion-service\n:8082] as IS {
  [IngestionController]
  [IngestionService]
  [IngestionProcessorFactory]
  [CsvIngestionProcessor]
}

component [pipeline-service\n:8083] as PS {
  [PipelineController]
  [PipelineService]
}

component [batch-service\n:8084] as BS {
  [BatchController]
  [BatchScheduleService]
  [BatchScheduler]
  [ForecastJob]
  [FilterEngine]
  [TransformationEngine]
}

database "templatedb\n(H2)" as TDB
database "ingestiondb\n(H2)" as IDB
database "pipelinedb\n(H2)" as PDB
database "batchdb\n(H2)" as BDB
cloud "External\nPrediction API" as EXT

TS --> TDB
IS --> IDB
PS --> PDB
BS --> BDB

IS ..> TS : REST
PS ..> TS : REST
BS ..> IS : REST
BS ..> PS : REST
BS ..> EXT : REST POST
@enduml
