spring.application.name=batch-service
server.port=8084

spring.datasource.url=jdbc:h2:mem:batchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

services.pipeline.url=http://localhost:8083
services.pipeline.uri=/api/pipelines/
services.ingestion.url=http://localhost:8082
services.ingestion.uri=/api/ingestion/jobs

scheduling.enabled=true
